name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Prevent multiple runs from interfering with each other
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  security:
    name: 'Security Scan'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: .

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "1.7.0"

    - name: Install tflint
      run: |
        curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Initialize tflint
      run: tflint --init

    - name: Install tfsec
      run: |
        curl -L https://github.com/aquasecurity/tfsec/releases/download/v1.28.1/tfsec-linux-amd64 -o tfsec
        chmod +x tfsec
        sudo mv tfsec /usr/local/bin/

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Run tflint
      run: tflint --recursive
      working-directory: .

    - name: Run tfsec
      run: tfsec .
      working-directory: .

    - name: Run Go Tests
      run: |
        cd test
        go mod tidy
        go test -v
      working-directory: . 