name: 'Security Scan'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Prevent multiple runs from interfering with each other
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  security:
    name: 'Security Scan'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: .

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install tflint
      run: |
        curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
        tflint --version

    - name: Run tflint
      run: |
        tflint --init
        tflint --recursive

    - name: Run tfsec
      uses: aquasecurity/tfsec-action@v1.0.0
      with:
        working-directory: .

    - name: Run checkov
      uses: bridgecrewio/checkov-action@master
      with:
        directory: .
        framework: terraform
        check: CKV_AWS_* 