name: 'Terraform CI'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: us-west-1
  AWS_PROFILE: turbot

# Prevent multiple runs from interfering with each other
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: ./turbot-assignment

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.7.5

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Run tflint
      uses: terraform-linters/tflint-action@v0.9.0
      with:
        working-directory: ./turbot-assignment
        args: --recursive

    - name: Run tfsec
      uses: aquasecurity/tfsec-action@v1.0.0
      with:
        working-directory: ./turbot-assignment

    - name: Run checkov
      uses: bridgecrewio/checkov-action@master
      with:
        directory: ./turbot-assignment
        framework: terraform
        check: CKV_AWS_*

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        profile-name: ${{ env.AWS_PROFILE }}

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install Terratest
      run: |
        go install github.com/gruntwork-io/terratest/modules/terraform@latest

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color

    - name: Run Tests
      run: |
        cd test
        go mod tidy
        go test -v

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve

    - name: Terraform Output
      if: steps.plan.outcome == 'success'
      run: terraform output
