name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

# Prevent multiple runs from interfering with each other
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-west-1
  TF_VAR_environment: dev  # Set environment to dev for GitHub Actions

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify AWS Authentication Prerequisites
        run: |
          if [ -z "${{ secrets.AWS_ACCOUNT_ID }}" ]; then
            echo "Error: AWS_ACCOUNT_ID secret is not set"
            exit 1
          fi

      - name: Configure AWS Credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/turbot-candidate4-github-oidc-role
          aws-region: ${{ env.AWS_REGION }}
          role-duration-seconds: 900

      - name: Verify AWS Authentication
        run: |
          # Verify AWS credentials
          if ! aws sts get-caller-identity &>/dev/null; then
            echo "Error: Failed to authenticate with AWS"
            exit 1
          fi
          
          # Verify permissions for testing
          echo "Verifying required AWS permissions..."
          
          # Test basic AWS API access
          aws ec2 describe-regions --region ${{ env.AWS_REGION }} || {
            echo "Error: Cannot access EC2 API"
            exit 1
          }

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.5"

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Go dependencies
        run: |
          cd test
          go mod download
          go mod tidy

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest boto3

      - name: Run Go tests
        run: |
          cd test
          go test -v ./...

      - name: Run Python tests
        run: |
          cd test
          pytest -v 